{
 "title": "ArgoWorkflow Metrics",
 "description": "Metrics from argoWF compatible with multi prometheus origins like Thanos.",
 "tags": [ "argo" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "lokids", "query": "loki" },
   { "name": "prometheusds", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_application=\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "dc",
    "label": "k8s_dc",
    "query": {
     "query": "label_values(argo_workflows_count,origin_prometheus) "
    }
   },
   {
    "name": "ns",
    "label": "k8s_ns",
    "query": {
     "query": "label_values(argo_workflows_count{origin_prometheus=~\"^$dc$\"},kubernetes_namespace) "
    }
   }
  ]
 },
 "panels": [
  { "title": "Currently", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"background-color:white; height:100%\">\n<img src=\"https://user-images.githubusercontent.com/25306803/43103633-a5d61dc4-8e83-11e8-9f0e-7ccdbee01eb6.png\" />\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "WF Pending",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\",status=\"Pending\"}"
    }
   ]
  },
  {
   "title": "WF Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\",status=\"Running\"}"
    }
   ]
  },
  {
   "title": "WF Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\",status=\"Error\"}"
    }
   ]
  },
  {
   "title": "WF Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\",status=\"Failed\"}"
    }
   ]
  },
  {
   "title": "WF Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\",status=\"Skipped\"}"
    }
   ]
  },
  {
   "title": "WF Succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\",status=\"Succeeded\"}"
    }
   ]
  },
  {
   "title": "Number of Workflows currently accessible by the controller by status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Workflow Status  ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\",status!~\"(Error|Failed)\"}",
     "legendFormat": " :  :  : "
    }
   ]
  },
  {
   "title": "Workflow Errors Alerting ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\",status=~\"(Error|Failed)\"}",
     "legendFormat": " :  :  : "
    }
   ]
  },
  {
   "title": "Histogram of durations of operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Workflow operation duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, origin_prometheus, kubernetes_namespace) (rate(argo_workflows_operation_duration_seconds_bucket{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"^$ns$\",origin_prometheus=~\"^$dc$\"}[5m])))",
     "legendFormat": " :  : 95th "
    }
   ]
  },
  { "title": "Adds to the queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Workflow queue adds ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(argo_workflows_queue_adds_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\"}[2m])",
     "legendFormat": " :  :  : "
    }
   ]
  },
  {
   "title": "Depth of the queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_queue_depth_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\"}",
     "legendFormat": " :  :  : "
    }
   ]
  },
  {
   "title": "Time objects spend waiting in the queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s", "label": "avg" }
   ],
   "targets": [
    {
     "expr": "rate(argo_workflows_queue_latency_sum{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"^$ns$\",queue_name=\"cron_wf_queue\"}[1m]) / rate(argo_workflows_queue_latency_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"^$ns$\",origin_prometheus=~\"^$dc$\",queue_name=\"cron_wf_queue\"}[1m])",
     "legendFormat": " :  :  : "
    },
    {
     "expr": "rate(argo_workflows_queue_latency_sum{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"^$ns$\",origin_prometheus=~\"^$dc$\",queue_name=\"pod_queue\"}[1m]) / rate(argo_workflows_queue_latency_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"^$ns$\",origin_prometheus=~\"^$dc$\",queue_name=\"pod_queue\"}[1m])",
     "legendFormat": " :  :  : "
    },
    {
     "expr": "rate(argo_workflows_queue_latency_sum{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"^$ns$\",origin_prometheus=~\"^$dc$\",queue_name=\"wf_cron_queue\"}[1m]) / rate(argo_workflows_queue_latency_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"^$ns$\",origin_prometheus=~\"^$dc$\",queue_name=\"wf_cron_queue\"}[1m])",
     "legendFormat": " :  :  : "
    },
    {
     "expr": "rate(argo_workflows_queue_latency_sum{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"^$ns$\",origin_prometheus=~\"^$dc$\",queue_name=\"workflow_queue\"}[1m]) / rate(argo_workflows_queue_latency_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"^$ns$\",origin_prometheus=~\"^$dc$\",queue_name=\"workflow_queue\"}[1m])",
     "legendFormat": " :  :  : "
    }
   ]
  },
  { "title": "Total number of log messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Log messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "count/sec" }
   ],
   "targets": [
    {
     "expr": "rate(log_messages{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",kubernetes_namespace=~\"$ns\",origin_prometheus=~\"^$dc$\"}[1m])",
     "legendFormat": " :  :  : "
    }
   ]
  }
 ]
}